INSERT INTO INDUSTRY (NAME,ID) VALUES ('Telecommunication',1)
INSERT INTO INDUSTRY (NAME,ID) VALUES ('Government',2)
INSERT INTO INDUSTRY (NAME,ID) VALUES ('Financial Services',3)
INSERT INTO INDUSTRY (NAME,ID) VALUES ('Life Sciences',4)
INSERT INTO INDUSTRY (NAME,ID) VALUES ('Manufacturing',5)
INSERT INTO INDUSTRY (NAME,ID) VALUES ('Education',6)


INSERT INTO COMPANY (NAME, ADDRESS, CITY, STATE, ZIP, PHONE, INDUSTRY,id) VALUES ("Adobe", "", "San Jose", "CA", "", "408", 1,1 )
INSERT INTO COMPANY (NAME, ADDRESS, CITY, STATE, ZIP, PHONE, INDUSTRY,id) VALUES ("SpringSource", "", "New York", "NY", "", "212", 2 ,2 )
INSERT INTO COMPANY (NAME, ADDRESS, CITY, STATE, ZIP, PHONE, INDUSTRY,id) VALUES ("Allaire", "", "Cambridge", "MA", "", "212", 3,3 )
INSERT INTO COMPANY (NAME, ADDRESS, CITY, STATE, ZIP, PHONE, INDUSTRY,id) VALUES ("Acme", "", "Denver", "CO", "", "212", 4,4 )
INSERT INTO COMPANY (NAME, ADDRESS, CITY, STATE, ZIP, PHONE, INDUSTRY,id) VALUES ("Acme", "", "Denver", "CO", "", "212", 4,5 )


